# /// script
# requires-python = ">=3.12"
# dependencies = ["jsonschema>=4.23", "pyyaml>=6"]
# ///
"""Render what the platform runs for each tenant, from tenants/*.yaml (ADR 14).

  * services/orchestrator/workspace.yaml  the platform's code location plus one per deployed tenant
  * compose.yaml, between the BEGIN/END markers  one Dagster code server per deployed tenant, one
    container per deployed tenant service, and the services' state volumes

Generated, committed, and checked: `make lint` fails if either differs from this output, so a
tenant file change and what it deploys are reviewed in the same PR.

Usage: uv run tenants/render.py [--check]
"""

from __future__ import annotations

import json
import sys

import check  # tenants/check.py, next to this file

ROOT = check.TENANTS.parent
WORKSPACE = ROOT / "services/orchestrator/workspace.yaml"
COMPOSE = ROOT / "compose.yaml"
BEGIN = (
    "  # BEGIN tenant code servers (generated by tenants/render.py: "
    "edit tenants/*.yaml, then `make tenants-render`)\n"
)
END = "  # END tenant code servers\n"
BEGIN_VOLUMES = "  # BEGIN tenant volumes (generated by tenants/render.py)\n"
END_VOLUMES = "  # END tenant volumes\n"
# Every deployed tenant workload together (code servers and services, by memoryMb): the canary
# (1024) plus markets-data's code server (1024), streams app (1536), producers (128 + 512).
# Sized for a 12 GB Docker VM on a 16 GB laptop (docs/scale.md, "The machine it runs on today"):
# on 28 Sep 2026 a driver per stream (5376 MB budget) ran the VM out of memory and Trino was
# OOM-killed, so markets-data merged its streams and the budget went back to 4608. Raising it is
# a platform decision, made in the PR that needs it, on a machine that has the memory.
MEMORY_BUDGET_MB = 4608
DEFAULT_CODE_MB = 1536


def memory_mb(t: dict) -> int:
    return t["codeLocation"].get("memoryMb", DEFAULT_CODE_MB)


def workloads(tenants: list[dict]) -> list[tuple[str, int]]:
    """(label, memoryMb) for every deployed code server and service."""
    out = []
    for t in tenants:
        if t["codeLocation"].get("deploy", False):
            out.append((f"{t['name']} code", memory_mb(t)))
        out += [
            (f"{t['name']} {s['name']}", s["memoryMb"])
            for s in t.get("services", [])
            if s.get("deploy", False)
        ]
    return out


def over_budget(tenants: list[dict]) -> str | None:
    loads = workloads(tenants)
    total = sum(mb for _, mb in loads)
    if total <= MEMORY_BUDGET_MB:
        return None
    each = ", ".join(f"{label} {mb}" for label, mb in loads)
    return (
        f"deployed tenant workloads need {total} MB ({each}), over the {MEMORY_BUDGET_MB} MB budget: "
        "lower memoryMb, undeploy one, or raise MEMORY_BUDGET_MB in tenants/render.py"
    )


def tenants() -> list[dict]:
    """Every tenant, validated and within the memory budget."""
    errors = check.check()
    all_tenants = [t for _, t in check.load()]
    if not errors and (problem := over_budget(all_tenants)):
        errors.append(problem)
    if errors:
        raise SystemExit("\n".join(f"FAIL {e}" for e in errors))
    return all_tenants


def deployed() -> list[dict]:
    """Tenants whose code server runs."""
    return [t for t in tenants() if t["codeLocation"].get("deploy", False)]


def deployed_services(ts: list[dict]) -> list[tuple[dict, dict]]:
    return [(t, s) for t in ts for s in t.get("services", []) if s.get("deploy", False)]


def secrets_mount(name: str) -> str:
    return f"""      # Only this tenant's folder of the secrets volume, never the platform's credentials.
      - type: volume
        source: platform-secrets
        target: /run/tenant-secrets
        read_only: true
        volume: {{ subpath: tenants/{name} }}
"""


def tenant_env(name: str) -> str:
    return f"""      AWS_REGION: us-east-1
      OPENLINEAGE_URL: http://marquez:5000
      KAFKA_BOOTSTRAP: kafka:9092
      TENANT: {name}
      # The platform's size (docs/scale.md): tenants choose how to run at it, e.g. streams as a
      # scheduled catch-up on a laptop, always on at full scale.
      PLATFORM_SCALE: ${{PLATFORM_SCALE:-laptop}}
      POLARIS_ENV_FILE: /run/tenant-secrets/polaris.env
"""


def service(t: dict) -> str:
    """A tenant's Dagster code server."""
    name, loc = t["name"], t["codeLocation"]
    return f"""  tenant-{name}-code:
    <<: *service
    profiles: [tenant-code, tenant-{name}]   # started by `make up` after tenant-reconcile has written its credentials
    image: {loc["image"]}
    # Runs execute here (the default run launcher), as the tenant's own Polaris identity.
    networks: [data, meta, stream]
    depends_on:
      db-migrate: {{ condition: service_completed_successfully }}
    entrypoint: ["dagster", "code-server", "start", "-h", "0.0.0.0", "-p", "4000", "-m", "{loc["module"]}"]
    environment:
      DAGSTER_HOME: /opt/dagster/home
      DAGSTER_DB_PASSWORD: ${{DAGSTER_DB_PASSWORD}}
{tenant_env(name)}    volumes:
      - ./services/orchestrator/dagster.yaml:/opt/dagster/home/dagster.yaml:ro
{secrets_mount(name)}    healthcheck:
      test: ["CMD", "dagster", "api", "grpc-health-check", "-p", "4000"]
      interval: 15s
      timeout: 10s
      retries: 20
      start_period: 30s
    mem_limit: {memory_mb(t)}m
"""


def secret_env(s: dict) -> str:
    """Where each secret the service uses sits (filled by `make tenant-secret`; may be missing)."""
    return "".join(
        f"      {x.upper().replace('-', '_')}_ENV_FILE: /run/tenant-secrets/{x}.env\n"
        for x in s.get("secrets", [])
    )


def workload(t: dict, s: dict) -> str:
    """A tenant's long-running service: same identity as its code server, no Dagster database."""
    name = t["name"]
    command = (
        f"    entrypoint: {json.dumps(s['command'])}\n    command: []\n"
        if s.get("command")
        else ""
    )
    state = (
        f"      - tenant-{name}-{s['name']}-state:/state\n"
        if s.get("stateVolume")
        else ""
    )
    return f"""  tenant-{name}-{s["name"]}:
    <<: *service
    profiles: [tenant-code, tenant-{name}]
    image: {s["image"]}
    # {s["description"]}
    networks: [data, stream]
{command}    environment:
{tenant_env(name)}{secret_env(s)}    volumes:
{secrets_mount(name)}{state}    mem_limit: {s["memoryMb"]}m
"""


def render_block(current: str, begin: str, end: str, body: str) -> str:
    if begin not in current or end not in current:
        raise SystemExit(f"{COMPOSE.name}: markers missing: {begin.strip()}")
    head, rest = current.split(begin, 1)
    _, tail = rest.split(end, 1)
    return head + begin + body + end + tail


def render_compose(current: str, ts: list[dict]) -> str:
    code = [service(t) for t in ts if t["codeLocation"].get("deploy", False)]
    services = [workload(t, s) for t, s in deployed_services(ts)]
    body = (
        "\n".join(code + services)
        if code or services
        else "  # (no tenant workload is deployed)\n"
    )
    volumes = [
        f"  tenant-{t['name']}-{s['name']}-state:\n"
        for t, s in deployed_services(ts)
        if s.get("stateVolume")
    ]
    out = render_block(current, BEGIN, END, body)
    return render_block(out, BEGIN_VOLUMES, END_VOLUMES, "".join(volumes))


def render_workspace(ts: list[dict]) -> str:
    out = [
        "# GENERATED by tenants/render.py from tenants/*.yaml: edit those, then `make tenants-render`.",
        "# The control plane loads pipeline code over gRPC from separately deployed code servers,",
        "# so pipeline changes redeploy without restarting the UI or the daemon (ADR 14: one per tenant).",
        "load_from:",
        "  - grpc_server:",
        "      host: dagster-code",
        "      port: 4000",
        "      location_name: lakehouse",
    ]
    for t in ts:
        if not t["codeLocation"].get("deploy", False):
            continue
        out += [
            "  - grpc_server:",
            f"      host: tenant-{t['name']}-code",
            "      port: 4000",
            f"      location_name: {t['name']}",
        ]
    return "\n".join(out) + "\n"


def main() -> int:
    ts = tenants()
    targets = {
        WORKSPACE: render_workspace(ts),
        COMPOSE: render_compose(COMPOSE.read_text(), ts),
    }
    stale = [p for p, text in targets.items() if p.read_text() != text]
    if "--check" in sys.argv:
        for p in stale:
            print(f"FAIL {p.relative_to(ROOT)} is stale: run `make tenants-render`")
        return 1 if stale else 0
    for p in stale:
        p.write_text(targets[p])
        print(f"wrote {p.relative_to(ROOT)}")
    loads = workloads(ts)
    used = sum(mb for _, mb in loads)
    print(
        f"OK   {len(loads)} tenant workload(s) deployed, {used} of {MEMORY_BUDGET_MB} MB budget"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
