# /// script
# requires-python = ">=3.12"
# dependencies = ["jsonschema>=4.23", "pyyaml>=6"]
# ///
"""Render what the platform runs for each tenant, from tenants/*.yaml (ADR 14).

  * services/orchestrator/workspace.yaml  the platform's code location plus one per deployed tenant
  * compose.yaml, between the BEGIN/END markers  one Dagster code server per deployed tenant

Generated, committed, and checked: `make lint` fails if either differs from this output, so a
tenant file change and what it deploys are reviewed in the same PR.

Usage: uv run tenants/render.py [--check]
"""

from __future__ import annotations

import sys
import check  # tenants/check.py, next to this file

ROOT = check.TENANTS.parent
WORKSPACE = ROOT / "services/orchestrator/workspace.yaml"
COMPOSE = ROOT / "compose.yaml"
BEGIN = (
    "  # BEGIN tenant code servers (generated by tenants/render.py: edit tenants/*.yaml, then `make tenants-render`)\n"
)
END = "  # END tenant code servers\n"
# All deployed tenants' code servers together (memoryMb, default 1536): two at the default.
# The platform alone uses about 6.6 GiB of an 11.7 GiB Docker VM (make mem, 27 Sep 2026), so
# raising this is a platform decision made in the PR that onboards the next tenant.
MEMORY_BUDGET_MB = 3072


def memory_mb(t: dict) -> int:
    return t["codeLocation"].get("memoryMb", 1536)


def over_budget(tenants: list[dict]) -> str | None:
    total = sum(memory_mb(t) for t in tenants)
    if total <= MEMORY_BUDGET_MB:
        return None
    each = ", ".join(f"{t['name']} {memory_mb(t)}" for t in tenants)
    return (
        f"deployed tenants need {total} MB ({each}), over the {MEMORY_BUDGET_MB} MB budget: "
        "lower codeLocation.memoryMb, undeploy one, or raise MEMORY_BUDGET_MB in tenants/render.py"
    )


def deployed() -> list[dict]:
    errors = check.check()
    tenants = [t for _, t in check.load() if t["codeLocation"].get("deploy", False)]
    if not errors and (problem := over_budget(tenants)):
        errors.append(problem)
    if errors:
        raise SystemExit("\n".join(f"FAIL {e}" for e in errors))
    return tenants


def service(t: dict) -> str:
    name, loc = t["name"], t["codeLocation"]
    return f"""  tenant-{name}-code:
    <<: *service
    profiles: [tenant-code]   # started by `make up` after tenant-reconcile has written its credentials
    image: {loc["image"]}
    # Runs execute here (the default run launcher), as the tenant's own Polaris identity.
    networks: [data, meta, stream]
    depends_on:
      db-migrate: {{ condition: service_completed_successfully }}
    entrypoint: ["dagster", "code-server", "start", "-h", "0.0.0.0", "-p", "4000", "-m", "{loc["module"]}"]
    environment:
      DAGSTER_HOME: /opt/dagster/home
      DAGSTER_DB_PASSWORD: ${{DAGSTER_DB_PASSWORD}}
      AWS_REGION: us-east-1
      OPENLINEAGE_URL: http://marquez:5000
      KAFKA_BOOTSTRAP: kafka:9092
      TENANT: {name}
      POLARIS_ENV_FILE: /run/tenant-secrets/polaris.env
    volumes:
      - ./services/orchestrator/dagster.yaml:/opt/dagster/home/dagster.yaml:ro
      # Only this tenant's folder of the secrets volume, never the platform's credentials.
      - type: volume
        source: platform-secrets
        target: /run/tenant-secrets
        read_only: true
        volume: {{ subpath: tenants/{name} }}
    healthcheck:
      test: ["CMD", "dagster", "api", "grpc-health-check", "-p", "4000"]
      interval: 15s
      timeout: 10s
      retries: 20
      start_period: 30s
    mem_limit: {memory_mb(t)}m
"""


def render_compose(current: str, tenants: list[dict]) -> str:
    if BEGIN not in current or END not in current:
        raise SystemExit(f"{COMPOSE.name}: tenant markers missing")
    head, rest = current.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    body = (
        "\n".join(service(t) for t in tenants)
        if tenants
        else "  # (no tenant has codeLocation.deploy: true)\n"
    )
    return head + BEGIN + body + END + tail


def render_workspace(tenants: list[dict]) -> str:
    out = [
        "# GENERATED by tenants/render.py from tenants/*.yaml: edit those, then `make tenants-render`.",
        "# The control plane loads pipeline code over gRPC from separately deployed code servers,",
        "# so pipeline changes redeploy without restarting the UI or the daemon (ADR 14: one per tenant).",
        "load_from:",
        "  - grpc_server:",
        "      host: dagster-code",
        "      port: 4000",
        "      location_name: lakehouse",
    ]
    for t in tenants:
        out += [
            "  - grpc_server:",
            f"      host: tenant-{t['name']}-code",
            "      port: 4000",
            f"      location_name: {t['name']}",
        ]
    return "\n".join(out) + "\n"


def main() -> int:
    tenants = deployed()
    targets = {
        WORKSPACE: render_workspace(tenants),
        COMPOSE: render_compose(COMPOSE.read_text(), tenants),
    }
    stale = [p for p, text in targets.items() if p.read_text() != text]
    if "--check" in sys.argv:
        for p in stale:
            print(f"FAIL {p.relative_to(ROOT)} is stale: run `make tenants-render`")
        return 1 if stale else 0
    for p in stale:
        p.write_text(targets[p])
        print(f"wrote {p.relative_to(ROOT)}")
    used = sum(memory_mb(t) for t in tenants)
    print(
        f"OK   {len(tenants)} tenant code server(s) deployed, {used} of {MEMORY_BUDGET_MB} MB budget"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
